### ISSUE TITLE
Config Overrides Overwrite One Another

### ISSUE THREAD

**Issue by squatched** [duo-labs/parliament#221]
If I specify something like:

```yaml
# Comment explaining why this exception pattern exists.
INVALID_ARN:
  ignore_locations:
    - Resource:
      - "^arn:aws:cloudformation:\\*:aws:.*$"

# ... several lines later ...

# Comment explaining why THIS exception pattern exists (spoiler, issue #220)
INVALID_ARN:
  ignore_locations:
    - Resource:
      - "^arn:aws:[^:]+:us-west-\\?:.*$"
```

I would expect the two exceptions to be combined. Instead, the second exceptional case overwrites the first and the policy statements that didn't used to trigger `INVALID_ARN` start triggering it again.

The fix is simple, I just combined the two. BUT, I figured this was worth reporting because I could easily see a situation where there are several exceptions and someone adding a new one doesn't realize it should be combined (maybe they don't notice an exception already exists), then the old exception starts being ignored and the person who added the new exception winds up tearing their hair out trying to figure out why their change introduced linting errors in documents they didn't touch.
